- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
    - name: nginx
      state: latest
  - name: start nginx
    ansible.builtin.service:
    - name: nginx
      state: installed
      enabled: yes



  


