- name: variables
  hosts: web
  vars:
    Course: "DevOps"
    Trainer: "Siva"
    Duration: "120hrs"
  become: no
  tasks:
  - name: Variables declaration
    ansible.builtin.debug:
      msg: "Learning {{Course}} with {{Trainer}} for {{Duration}}"