- name: variables
  hosts: localhost
  vars:
    Course: "Terraform"
    Trainer: "Sivakumar"
    Duration: "15hrs"
  become: no
  tasks:
  - name: Variables declaration
    ansible.builtin.debug:
      msg: "Learning {{Course}} with {{Trainer}} for {{Duration}}"