- name: varibles
  hosts: localhost
  become: no
  vars:
    Course: "Terraform"
    Trainer: "Siva"
    Duration: "120hrs"
  tasks:
  - name: Overriding check
    vars:
      Course: "DevOps"
    ansible.builtin.debug:
      msg: "Override DevOps: {{Course}} {{Trainer}} {{Duration}}"
  - name: Inheritance check
    ansible.builtin.debug:
      msg: "Inheritance Terraform: {{Course}} {{Trainer}} {{Duration}}"      



               