- name: var with prompt
  hosts: localhost
  become: no
  vars_prompt:
  - name: USERNAME
    prompt: "Please enter user name"
    private: no
  - name: PASSWORD
    prompt: "Please enter password"
    private: yes  

  tasks:
  - name: var with prompt
    ansible.builtin.debug:
      msg:  "Username: {{USERNAME}}, Password:{{PASSWORD}}"  