- name: var pre check
  hosts: localhost
  become: no 
  vars:
  - WISHES: "Playlevel GM"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: WISHES
    prompt: "from Prompt: GM"
    private: false
  tasks:
  - name: Task level
    # vars:
    # - WISHES: "Tasklevel GM"
    ansible.builtin.debug:
      msg:  "{{WISHES}}"


  

