- name: var pre check
  hosts: localhost
  vars:
  - WISHES: "Play level:GM"
  vars_promt:
  - name: WISHES
    prompt: "Enter wishes from prompt format: prompt GM"
    private: false

  vars_file:
  - vars.yaml
  become: no
  tasks:
  - name: var pre check2
    vars:
    - WISHES: "Task level:GM"
    ansible.builtin.debug:
      msg: "{{WISHES}}"

