- name: id expense check
  hosts: web
  become: yes
  tasks:
  - name: id check
    ansible.builtin.command:  id expense2
    register: USER
    ignore_errors: true

  - name: 
    ansible.builtin.debug:
      msg:  "{{USER}}"  

  - name:
    ansible.builtin.command:  useradd expense1
    when: USER.rc  !=  0    



  - name: print hello
    ansible.builtin.debug:
      msg:  "Hello"  







