- name: id expense check
  hosts: web
  become: yes
  tasks:
  - name: id check
    ansible.builtin.command:  id expense1
    register: USER
    ignore_errors: false

  - name: 
    ansible.builtin.debug:
      msg:  "{{USER}}"  



  - name: print hello
    ansible.builtin.debug:
      msg:  "Hello"  







