- name: Conditions
  hosts: web
  become: yes
  tasks:
  - name: id expense task
    ansible.builtin.command:  id expense
    register: USER

  - name: user information
    ansible.builtin.debug:
      msg: "{{USER}}"

  - name: hello
    ansible.builtin.debug:
    msg: "Hello"    



  
  