- name: fun check
  hosts: localhost
  become: no
  tasks:
  - name: var check
    ansible.builtin.debug:
      msg: "{{message | default('NNR is great')}}"

- name: upper case
  hosts: localhost
  become: no 
  vars:
    greetings: "Hi , nnr is good boy in the world"
  tasks:
  - name: upper case check
    ansible.builtin.debug:
      msg: "{{greetings | upper}}"

- name: lower case
  hosts: localhost
  become: no
  vars:
    greetings: "HI , GOOD MORNING GLABAOR"
  tasks:
  - name: lower case check
    ansible.builtin.debug:
      msg: "{{greetings | lower}}"

- name: unique numbers
  hosts: localhost
  become: no
  vars:
    numbers: [10,20,5,5,10,20,30,40]
  tasks:
  - name: "Unique numbers"
    ansible.builtin.debug:
      msg: "{{numbers | unique}}" 

- name: max and min
  hosts: localhost
  become: no 
  vars:
    ages: [25,35,67,89,99,100]
  tasks:
  - name: "max and min check"
    ansible.builtin.debug:
      msg: "min: {{ages | min }} max: {{ages | max }}"  

- name: list2items
  hosts: localhost
  become: no 
  vars:
    mydict:
    - Course: Devops
    - Training: Siva
    - Duration: 120hours
  tasks:
  - name: print list2item
    ansible.builtin.debug:
      msg: "Before the dict:{{mydict}}"  



