- name: DB
  hosts: localhost
  become: yes
  vars:
    login_host: db.daws78s-nnr.online
  vars_prompt:
  - name: DB_PASSWORD
    prompt: "Pls enter db password:::"
    private: no

  tasks:
  - name: install mysql-server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: start mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Install pip
    ansible.builtin.pip:
      name: 
      - PyMySQL
      - cryptography
      executable: pip3.9 

  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{DB_PASSWORD}}"
      login_host: "{{login_host}}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print connection output
    ansible.builtin.debug:
      msg: "{{mysql_connection_output}}"

       
      



